### ISSUE TITLE
There was a problem logging you in. Please contact your administrator for assistance.  More information about this error

### ISSUE THREAD

**Issue by rpowellSTUK** [MSOpenTech/o365-moodle#2085]
Hi,

We have been using the plugin without issue for a year now and all of a sudden everyone is getting the error:
There was a problem logging you in. Please contact your administrator for assistance.

[More information about this error](https://docs.moodle.org/311/en/error/auth_oidc/errorauthgeneral)

I think it is something todo with the connection between the Plugin and Azure, but I am unable to login even has an admin to get to the settings so I can check everything.

What could be causing the issue that it suddently happens, no settings were changed by admin to cause this.

Many Thanks,
R

**Comment by nenorojas** [comment]
Hi,

Without more details, my guess is that the secret of the application expired. So you need to login as Moodle administrator using a manual account to replace with a new valid secret. The maximum expiration of a secret is 2 years.

Regards

Oswaldo

**Comment by rpowellSTUK** [comment]
@nenorojas , we were suspecting the same thing. The issue we have is that we cannot access the local admin account in order to reset the security certificate. We have asked Microsoft if there is anyway they can extend the previous certificate.

@mmulrthelp , how were you able to get to login to the local admin account?

Does anyone know where the security certification details are stored either in a config file or database field that I can use to update.

Many Thanks for both of your responses.

**Comment by mmulrthelp** [comment]
Hi @rpowellSTUK try changing the auth of your username to manual within the database, this should get you back in as a site admin. But your password in the following is not cached, it might have to be inserted as a hashed value, I'm unsure.. do you know anyone elses manual password which you can copy that salt across to your mdl_user line ?

SELECT * FROM moodle.mdl_user where username like '<YOURUSERNAME>%' and auth = 'oidc';

**Comment by nenorojas** [comment]
@rpowellSTUK , after you change the oidc to manual directly in the database, you can use the Moodle forget password feature to get a new one via email.

**Comment by rpowellSTUK** [comment]
@mmulrthelp and @nenorojas Thankyou both for your input.
I have made the changes in the database but it still seems to be looping through the Azure authorisation, I think this is because we dont use a login page, the login button at the top directly links straight to Azure. I have tried to go to /login/index.php and to /login/index1.php which was meant to be an alternative login page however they both try to use SSO again and return the same message.

Is there anyway to load a login page? I have a manual Admin account already and if I could get to a login page that accepts manual logins I could use that.

Many Thanks again for all your help and support.

**Comment by nenorojas** [comment]
Try, /login/index.php?noredirect=1. You might need to enable that option first in auth_oidc settings page.

**Comment by rpowellSTUK** [comment]
Where would I enable the setting in the auth_oidc settings page?

**Comment by rpowellSTUK** [comment]
Ok that has gotten me to the login page, but the old admin user it says invalid login and if I copy the hashed password in to my account on the database it also says invalid login. this is telling me that the password is wrong.
How do I create a hashed password I can type in to the database?

**Comment by weilai-irl** [comment]
Hi @rpowellSTUK,

You can try this command in SQL:
`UPDATE mdl_user SET password=md5('NEW_PASSWORD') WHERE id = YOUR_USER_ID;`

Providing your account is still using auth_manual and the account is not suspended/deleted, this should allow you to login.

Regards,
Lai

**Comment by rpowellSTUK** [comment]
Thanks All,

So I have gotten in :) yay, now for the confusing thing.

Ends up it is not todo with expired certificate or even a communications error with Azure. For some reason everyones accounts have been suspended.

Anyone got a clue as to how that might of happened or how I could look it up?

Regards,

Rob

**Comment by mmulrthelp** [comment]
@rpowellSTUK That's the same thing we saw, the latest code has fixed this issue. see https://github.com/microsoft/o365-moodle/issues/2048

My documentation which I wrote on our end :

:thinking: Problem
Users are blocked from logging in to Moodle, this has now occurred twice in the past. Both times after a new version of the code was deployed.

:seedling: Solution

Check the last ran '[Sync users with Azure AD](https://moodle.mmu.ac.uk/admin/tasklogs.php?filter=local_o365%5Ctask%5Cusersync)' scheduled task within Moodle. 

Use Crtl+F to search log file, search for ‘Suspending deleted users’ are there a load of entries where it says suspending user x, y & z 

...... Start suspend/delete users feature...
...... Error in full usersync: Error in API call.
...... Resetting skip and delta tokens.
...... Suspending deleted users...
......... Could not find user 'user1' in Azure AD. Suspending user...
......... Could not find user 'user2' in Azure AD. Suspending user...
......... Could not find user 'user3' in Azure AD. Suspending user...
......... Could not find user 'user4' in Azure AD. Suspending user...
......... Could not find user 'user5' in Azure AD. Suspending user...
Fast fix, copy all suspended users into Notepad, strip off anything apart from user ID using 'Alt' drag method.

Copy that into a Excel file column one called ‘username’ & in column 2 called ‘suspended’, add in a '0' for all instances, save as a .CSV file.

Login to Moodle as a admin, if in the case of 11/05/2022 issue if it has suspended all site admins then Ray has a local admin account. Login within a incognito window to https://moodle.mmu.ac.uk/?noredirect=1 then go to https://moodle.mmu.ac.uk/?noredirect=1?admin=yes to get to the backdoor manual login fields

Site administration / Users / Accounts / Upload users. Choose the .CSV saved from Excel with the IDs. Change Settings ‘Upload type’ to ‘Update existing users only’. now click ‘Upload users' button.

This will revert the process of the last sync, unsuspending the suspended users.

Get some one who was suspended to try and login again.

Switch off the [3rd option here](<moodle site>/admin/settings.php?section=local_o365&s_local_o365_tabs=1) until you have figured out why this is happening. ‘Suspend previously synced accounts in Moodle when they are deleted from Azure AD’.

Site Admins cannot be enabled via the above method, they need to be unsuspended via the eye icon in Users > Accounts > Browse list of users

**Comment by mmulrthelp** [comment]
Hi @micluka you just need to unsuspend them with a CSV like this 
![image](https://user-images.githubusercontent.com/16646247/179965396-4ba48551-0d8c-48d1-991d-23d67374b29f.png)
You do not have to specify the authentication method to un-suspend accounts as they already exist on your system.

**Comment by micluka** [comment]
see image shows what i mean,
![upload setting](https://user-images.githubusercontent.com/61785387/179974944-d0049f42-f4b6-4710-93ab-2ae92e7e9f54.png)

**Comment by micluka** [comment]
see image shows the setting I'm asking about highlighted
![upload setting](https://user-images.githubusercontent.com/61785387/179975379-942566fa-fae2-49bf-ab3d-591ee728b1da.png)
 in red:

**Comment by mmulrthelp** [comment]
I get you now @micluka i only ever set the following, I do not go near what is in 'Default values'
![image](https://user-images.githubusercontent.com/16646247/179978175-2407f84b-fc5e-4d54-a347-ca951337c5b7.png)

Regards,
Ray.

**Comment by micluka** [comment]
@mmulrthelp Do you believe that leaving the default values set to manual account will prevent all of our users from becoming manual accounts since you are aware that all of our users have "oidc" accounts?

**Comment by mmulrthelp** [comment]
Yes @micluka, as I've had to do this multiple times before and it has not been an issue - if you are unsure and would like to test before doing all at once, trim the CSV to say 5 users and check those over after doing them.

**Comment by micluka** [comment]
Thanksssss,
I use.CSV files to activate every one of them.
