### ISSUE TITLE
Getting php errors after saving user profile field settings.

### ISSUE THREAD

**Issue by sushantgawali** [MSOpenTech/o365-moodle#29]
Steps to reproduce:

1. Login using admin privileges.
2. Go to Site Administration > Users > Accounts > User profile fields.
3. Click on edit icon of any field.
4. Click save on edit form.

It will show errors for both the fields. I have updated latest code from master branch on server.

Link : http://mofficewin1.cloudapp.net
Login : admin / Pwd&0011

**Comment by jamesmcq** [comment]
Can't reproduce this - if the problem is still present using the current versions of the plugins please create a new issue.
