### ISSUE TITLE
Little fix in jwt.php

### ISSUE THREAD

**Issue by andruhovski** [MSOpenTech/o365-moodle#34]
I got the error. 
 
PHP 5.4.24 Default exception handler: Could not read JWT payload. 
Debug: 
Error code: errorjwtbadpayload 
* line 71 of \auth\oidc\classes\jwt.php: moodle_exception thrown
* line 98 of \auth\oidc\classes\jwt.php: call to auth_oidc\jwt::decode()
* line 159 of \auth\oidc\auth.php: call to auth_oidc\jwt::instance_from_encoded()
* line 33 of \auth\oidc\index.php: call to auth_plugin_oidc->handleauthresponse()

The error is caused by incorrect working function base64_decode() in file o365-moodle/blob/master/auth/oidc/classes/jwt.php
when the user has Cyrillic characters in the name or in the surname.

In my case all works fine with change line 84: $body = base64_decode($jwtparts[1]);
to line 84: $body = base64_decode(strtr($jwtparts[1] , '-_,', '+/='));

**Comment by jamesmcq** [comment]
Thanks for the report! I've added this to our backlog and should be worked on shortly.

**Comment by jamesmcq** [comment]
Hi andruhovski, I've tried this out using Cyrillic characters and can't reproduce the error you're getting. Can you give me some more information about the characters used? Don't post the full name due to privacy concerns, but any non-identifiable information would be helpful. Thanks!

**Comment by andruhovski** [comment]
I created test user Anton Antonov (anton@kpnu.km.ua) with  first name Антон, and last name Антонов. Licence: Office 365 Education E1 for Students. Other information (such us job title, etc.) was not added.

 

On server with moodle I install oidc as descibed in https://msopentech.com/wp-content/uploads/Office-365-plugins-for-Moodle-documentation.pdf. 

When I try to login with antov@kpnu.km.ua I get an error Could not read JWT payload.

 

My next step was to investiagte the contents of the variable $jwtparts[1]. Here is my result in var_dump($jwtparts[1]);

string(796) "eyJhdWQiOiI2YmMyMDhjNS0zM2E5LTRiNDAtOTUzMC0zMTJkMzE5N2E0MzIiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC81ZDY2OGY3My0yODRkLTQ5Y2MtODY2Ny0wNTM5ZTU2ZTc0ZjMvIiwiaWF0IjoxNDIzMTQ0Mzc5LCJuYmYiOjE0MjMxNDQzNzksImV4cCI6MTQyMzE0ODI3OSwidmVyIjoiMS4wIiwidGlkIjoiNWQ2NjhmNzMtMjg0ZC00OWNjLTg2NjctMDUzOWU1NmU3NGYzIiwiYW1yIjpbInB3ZCJdLCJvaWQiOiIzOGI4Nzk4Yi0wZjlkLTRhYmUtYTI1YS1mNTFmOWQ1Njg3MjUiLCJ1cG4iOiJhbnRvbkBrcG51LmttLnVhIiwic3ViIjoiRDNyb1gxLUZFNGdJeFBBSTg3azZJOV9TbHN1dE5MRmxOcHJOazkwcUhhdyIsImdpdmVuX25hbWUiOiLQkNC90YLQvtC9IiwiZmFtaWx5X25hbWUiOiLQkNC90YLQvtC90L7QsiIsIm5hbWUiOiLQkNC90YLQvtC9INCQ0L3RgtC-0L3QvtCyIiwidW5pcXVlX25hbWUiOiJhbnRvbkBrcG51LmttLnVhIiwibm9uY2UiOiJONTRkMzc2YjdhNjdkOCIsInB3ZF9leHAiOiI3NDMzMjk4IiwicHdkX3VybCI6Imh0dHBzOi8vcG9ydGFsLm1pY3Jvc29mdG9ubGluZS5jb20vQ2hhbmdlUGFzc3dvcmQuYXNweCJ9"

…and result of base64 decode is like this 

  

IMHO in PHP 5.4.24 function base64_decode() working incorrectly and JSON string is corrupted. After some experiments (change first/last name to latin) and web searching I came to conclusion, that this function incorrectly decoded Cyrillic characters (or Cyrillic characters as Unicode characters). 

An idea to replacement I taken from http://stackoverflow.com/questions/1374753/passing-base64-encoded-strings-in-url. After fix I got an normal JSON string like this

string(597) "{"aud":"6bc208c5-33a9-4b40-9530-312d3197a432","iss":"https://sts.windows.net/5d668f73-284d-49cc-8667-0539e56e74f3/","iat":1423146198,"nbf":1423146198,"exp":1423150098,"ver":"1.0","tid":"5d668f73-284d-49cc-8667-0539e56e74f3","amr":["pwd"],"oid":"38b8798b-0f9d-4abe-a25a-f51f9d568725","upn":"anton@kpnu.km.ua","sub":"D3roX1-FE4gIxPAI87k6I9_SlsutNLFlNprNk90qHaw","given_name":"Антон","family_name":"Антонов","name":"Антон Антонов", "unique_name":"anton@kpnu.km.ua", "nonce":"N54d37dd1f25ab", "pwd_exp":"7431479","pwd_url":"https://portal.microsoftonline.com/ChangePassword.aspx"}"

My Moodle is hosted on Windows 2008 Server Web/IIS 7/PHP 5.2.24/MS SQL Express 2008 R2. 

That’s all

P.S. moodle.kpnu.km.ua is server for testing without any personal data, and user anton@kpnu.km.ua is not a real person (I will remove this user, after finish this letter.).



Best regards, Andriy Andruhovski.
Sent from Windows Mail





From: James McQuillan
Sent: ‎Thursday‎, ‎February‎ ‎5‎, ‎2015 ‎12‎:‎17‎ ‎PM
To: MSOpenTech/o365-moodle
Cc: Andriy Andruhovski





Hi andruhovski, I've tried this out using Cyrillic characters and can't reproduce the error you're getting. Can you give me some more information about the characters used? Don't post the full name due to privacy concerns, but any non-identifiable information would be helpful. Thanks!

**Comment by jamesmcq** [comment]
Thanks Andriy! Really appreciate the additional information you've provided. Will look into this further and post when I have more information.

**Comment by jamesmcq** [comment]
Thanks Andriy! This change has been released.
