### ISSUE TITLE
Office 365 Account | OneDrive Business

### ISSUE THREAD

**Issue by schjan** [MSOpenTech/o365-moodle#35]
If the OneNote submission / feedback system would work directly with the Office 365 **moodle-auth_oidc** Plugin and OneDrive Business, the user wouldn't need to have a Microsoft account but only the Office 365 account which is automatically connected because of SSO and the notebooks would directly be synced with the users business OneDrive Account.

**Comment by jamesmcq** [comment]
Currently that is not possible as the accounts used for OneNote and OneDrive for Business are separate on the Microsoft side - they exist as two independent products. We are watching this and if/when it becomes possible we will be implementing it. However, we do not have a timeline on when or if this will be available.

**Comment by martincai** [comment]
FYI. OneDrive for personal via http/https is blocked by the China firewall, which leads to the OneNote assignment creation step unusable in China.

**Comment by jamesmcq** [comment]
@schjan Just an update - o365 access to OneNote is currently being worked on and expected to be released in the next couple weeks.

**Comment by jamesmcq** [comment]
@schjan This has been released - Office365 customers can now use OneNote with their Office365 accounts.
