### ISSUE TITLE
Please separate these plugins into separate repos

### ISSUE THREAD

**Issue by mattgibson** [MSOpenTech/o365-moodle#37]
We cannot manage these plugins using git submodules in our Moodle build because they are all in the same repo. It would be far better to have them separate so that we can import the ones we need and update them easily.

**Comment by jamesmcq** [comment]
This is actually the development repository, the plugins do exist already in independent repositories and changes are pushed to these independent repositories at each release. Links to each of these repositories are available in this repository's readme.
