### ISSUE TITLE
O365 China API endpoints are not included in the code

### ISSUE THREAD

**Issue by martincai** [MSOpenTech/o365-moodle#41]
O365 is a separate instance from rest of world. It's API endpoints are different. Please see: https://msdn.microsoft.com/en-us/office/office365/api/o365-china-endpoints

Forking the code to create a China version of the plug-ins seems unnecessary. Can we include a switch which toggles the specific set of API endpoints in plug-in configuration?

**Comment by jamesmcq** [comment]
Hi Martin,

The latest release includes a setting to use the Chinese endpoints. Can you try the newest versions and let me know if that works for you?

Thanks

**Comment by martincai** [comment]
Great!  Saw the latest plug-ins in the gallery.  There is still a little issue with getting O365 directory to sync with Azure directory in China.  Once that's resolved, I will test it right the way.  Thanks!

**Comment by jamesmcq** [comment]
Re: syncing with Azure directory in China - can you refresh my memory on that? Is there a Github issue or was that discussed over email?

**Comment by martincai** [comment]
It appears to be an Azure issue in China only. It's being worked on. Not related to Github or this project.

**Comment by jamesmcq** [comment]
Okay thanks - let me know how the testing goes once that's resolved. Thanks!

**Comment by martincai** [comment]
I finally managed to get a Office 365 (China) login and AAD (China) login. Not an easy job. =)  Started to validate the China endpoints. But, every time after logging into Office 365, Moodle displayed error "Auth code not received."  China Auth endpoint and Token endpoint are https://login.chinacloudapi.cn instead of login.windows.net.  Not sure if that's the problem. I'd be more than happy to troubleshoot with some debugging instructions. Thanks.

**Comment by martincai** [comment]
By the way, I am using Moodle 2.9.1 and the 2.9 version of the plugins.

**Comment by jamesmcq** [comment]
Hi Martin - The auth and token endpoint are user-configurable in the OpenID Connect plugin, login.windows.net is just the default - my thought was users using the Chinese API would be able to enter the value there.

**Comment by martincai** [comment]
I replaced the auth and token endpoints inside the OpenID Connect plugin with the China endpoints. I am getting "Auth code not received" error after entering O365 credential. If there is a way for me to find out whether it's the AAD (China) auth/token endpoints being broken or some place inside the plugin that is causing the error, I'd like to try debugging it. Now, I am blocked by not knowing where the real root cause actually is at. Any help is very much appreciated.

**Comment by jamesmcq** [comment]
What do you have for the auth + token endpoints? Do you have test credentials available I could use?

**Comment by martincai** [comment]
I am sorting out another little issue on the Azure side.  Basically, I am trying to eliminate variables that could have caused the problem.  I will share with you a test credential once I am ready on this side.  Thanks again, James.

**Comment by martincai** [comment]
Hi James,

Here are the credentials to my Moodle, O365, Azure environments in China.  Could you please take a look?  The password for all of these accounts is:  Passw0rd!

Moodle
http://moodle-o365.chinacloudapp.cn:8029/
User:  admin

Office 365 (China)
https://portal.partner.microsoftonline.cn/
Admin User:  james@msopentecho365.partner.onmschina.cn
User:  teacher1@msopentecho365.partner.onmschina.cn
User:  student1@msopentecho365.partner.onmschina.cn

Azure (China)
https://manage.windowsazure.cn/
Admin User:  james@msopentecho365.partner.onmschina.cn
Please note that this Azure account is for AD usage only, so do not create any other service there.

**Comment by jamesmcq** [comment]
Hi Martin, I had to delete that last message since it contained credentials and this is public - you may want to change the password on that account. You can can email me at james.mcquillan@remote-learner.net

**Comment by jamesmcq** [comment]
Hi Martin,

The Moodle plugin database (after a long delay!) has been updated with the current version of the plugins. This should resolve the issues we discussed, including the "resource" parameter in OpenID Connect. Can you update and test whether any additional changes are needed?
