### ISSUE TITLE
Moodle is setting up this SharePoint site

### ISSUE THREAD

**Issue by veshant** [MSOpenTech/o365-moodle#45]
When I enter the sharepoint url, the message "Moodle is setting up this SharePoint site" is there and it is loading.  When I refresh, it doesn't change.  I have waited a day.  Anyone know what's going on?

**Comment by jamesmcq** [comment]
Hi Veshant,

The SharePoint site is set up during the Moodle cron, so this must run before that message will change.

Thanks,
- James

**Comment by veshant** [comment]
Hey James,
Thanks!  It works!

I have another issue though,  I have "Sync users from AzureAD" checked, however, the users are not syncing.  Even after cron execution.

Also, under "Application Permissions" I get that these are missing:
Directory.Read
UserProfile.Read
AllSites.Read
AllSites.Write
AllSites.Manage
AllSites.FullControl
MyFiles.Read
MyFiles.Write
Calendars.Read
Calendars.ReadWrite
Notes.ReadWrite
Notes.Read
Notes.Create

In my Azure AD, I have given delegated access to all.

If you want me to create a new issue, let me know and I'll get it done.  Otherwise, I could really use your help.  Thanks! :)

**Comment by jamesmcq** [comment]
@veshant Good to know the SharePoint issue is resolved. 

What version of the plugins are you running? (Specifically what version of local_o365?)

**Comment by veshant** [comment]
@jamesmcq I am running version 29.  Just downloaded from the git a day ago.

**Comment by veshant** [comment]
I also tested on a different setup with the latest version on the middle plugins site, I believe it's version 28.  On that, the only permissions missing were the ".notes" (no issue because I have not setup one note).  However, on that site as well, the users were not syncing.
