### ISSUE TITLE
Settings page produces debugging output

### ISSUE THREAD

**Issue by techxplorer** [MSOpenTech/o365-moodle#47]
Hi,

The `local/o365/settings.php` file can produce debugging output due to the way that it requires the jQuery library.

For example:

```php
$PAGE->requires->jquery();
```

Should really be:

```php
if (!$PAGE->requires->is_head_done()) {
    $PAGE->requires->jquery();
}
```

This ensures that the jQuery library is only included / loaded when it is safe to do so. 

Steps to replicate:

1. Login is admin
2. Access a users profile
3. Login as that user
4. See the debugging output displayed

**Comment by jamesmcq** [comment]
Thanks techxplorer! I'll include that in the next release. (or feel free to submit a pull request if you want the commit).

**Comment by jamesmcq** [comment]
This is now in stable, thanks!
