### ISSUE TITLE
repository/onenote can produce debugging output during install

### ISSUE THREAD

**Issue by techxplorer** [MSOpenTech/o365-moodle#48]
Hi,

The `local/onenote/classes/api/base.php` file can produce debugging output during installation of the plugin. 

The suggested fix is to change:

```php
$iso365user = ($USER->auth === 'oidc' && class_exists('\local_o365\rest\onenote')) ? true : false;
```
to:
```php
$iso365user = (isset($USER->auth) && $USER->auth === 'oidc' && class_exists('\local_o365\rest\onenote')) ? true : false;
```
Debugging output can cause unit tests to fail, which can be problematic.

**Comment by jamesmcq** [comment]
Thanks again techxplorer! I'll include that in the next release as well. (or, again, feel free to submit a pull request if you want the commit).

**Comment by jamesmcq** [comment]
This line has been replaced with a better way to detect O365 connection so this issue is resolved. Thanks for the report!
