### ISSUE TITLE
Error when creating user groups in Office 365

### ISSUE THREAD

**Issue by grant007** [MSOpenTech/o365-moodle#51]
In my case, no User Groups are being created in Office 365. I have captured the following output from the cron job which seems to indicate an error but I do not how to interpret it nor how to remedy.

Execute scheduled task: Create user groups in Office365
... started 19:45:06. Current memory use 74.5MB.
Could not create group for course #4
array(1) {
  ["odata.error"]=>
  array(3) {
    ["code"]=>
    string(18) "Request_BadRequest"
    ["message"]=>
    array(2) {
      ["lang"]=>
      string(2) "en"
      ["value"]=>
      string(72) "Invalid value specified for property 'mailNickname' of resource 'Group'."
    }
    ["values"]=>
    array(2) {
      [0]=>
      array(2) {
        ["item"]=>
        string(12) "PropertyName"
        ["value"]=>
        string(12) "mailNickname"
      }
      [1]=>
      array(2) {
        ["item"]=>
        string(17) "PropertyErrorCode"
        ["value"]=>
        string(12) "InvalidValue"
      }
    }
  }
}
Created group 5facffc9-990a-43d2-8e3b-16e4ab819254 for course #6
Recorded group object (5facffc9-990a-43d2-8e3b-16e4ab819254) into object table with record id 4
Waiting 10 seconds for group to register...
Adding users to group (5facffc9-990a-43d2-8e3b-16e4ab819254)
Added user #9 (77d36274-2d34-4620-b1d7-7b5e441e1701)
Added user #10 (6fa12531-7e70-4c24-8457-9924c3d81f2d)
Added user #8 (36c1301a-6ae1-4752-b850-7ce99cfa3381)
... used 12 dbqueries
... used 19.472978830338 seconds
Scheduled task complete: Create user groups in Office365
Execute scheduled task: Sync o365 events in to Moodle
... started 19:45:25. Current memory use 75MB.
Bad response received when fetching events.
... used 5 dbqueries
... used 1.9638118743896 seconds
Scheduled task complete: Sync o365 events in to Moodle

Please advise.

**Comment by grant007** [comment]
I think I discovered something. In a previous test exercise, I created a course Algebra1 and a User Group named Algebra1was successfully created in Office 365. When the testing was over, the course and User Group were deleted. Now a new course was recreated (named the same) and it cannot create a User Group. But if I create a brand new course with an original name, a User Group is created successfully.

**Comment by grant007** [comment]
Any update on this? Both User Groups and Sharepoint Sites features are not working. Groups are being created for each Course but no Members are being populated.
I only have 5 days until school starts and  I have run out of time to get things ready before school starts.

**Comment by jamesmcq** [comment]
Hi Grant, 

The "Added user" line in the trace you posted indicates the o365 API responded successfully so the user *should* be part of the group... Just to confirm, where are you looking to see the members of the group? The Office365 admin app has a "groups" section that should list the groups + members, is that where you're looking?

**Comment by grant007** [comment]
I have look in both Admin - Groups and in the User Group itself and neither
have any members. No teacher, no students.

On Mon, Aug 10, 2015 at 11:57 AM, James McQuillan <notifications@github.com>
wrote:

> Hi Grant,
>
> The "Added user" line in the trace you posted indicates the o365 API
> responded successfully so the user *should* be part of the group... Just
> to confirm, where are you looking to see the members of the group? The
> Office365 admin app has a "groups" section that should list the groups +
> members, is that where you're looking?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MSOpenTech/o365-moodle/issues/51#issuecomment-129505727>
> .
>



-- 
Grant Stone

**Comment by jamesmcq** [comment]
The error indicated in your first post about creating user groups and mailNickname is fixed in master and will be included in the next release.
