### ISSUE TITLE
Multi Tenant Support

### ISSUE THREAD

**Issue by veshant** [MSOpenTech/o365-moodle#52]
Would be great if the plugin supported multiple tenants.  We need to separate our students from faculty for security reasons, so they will be on two tenants.

**Comment by jamesmcq** [comment]
Hi Veshant, 

Interesting proposal - can you expand a bit on what you would need for your setup? Different settings per tenant for example?

**Comment by veshant** [comment]
Hi James,
Basically we would need to propagate users from both tenants and allow both to login.  If the other functions such as the OneDrive repo and SharePoint sites would work, that would be nice, but that is secondary and not a requirement.

**Comment by jamesmcq** [comment]
Ah okay you're specifically interested in having multiple *Azure* tenants, correct? (I know at one point Moodle was doing "multi-tenant Moodle", which is something different.)

**Comment by veshant** [comment]
Yup, exactly. Multiple Azure tenants.

I was not aware of the multi-tenant Moodle.  Just looked it up and that looks interesting. Thanks for that info!

**Comment by veshant** [comment]
Hey James,

Just wanted to see if you plan on adding this to the roadmap.  Thanks.

**Comment by HadynM-TWoA** [comment]
Upvote.

Regards
Hadyn Morgan

**Comment by veshant** [comment]
Hi James,

Do you have any updates on this?

**Comment by jamesmcq** [comment]
Hi Veshant, all - This is currently on our backlog. I don't have a specific timeline but there is definitely interest on our side in implementing this. Appreciate the suggestion!

**Comment by HadynM-TWoA** [comment]
Hi James, is the backlog public?

**Comment by jamesmcq** [comment]
The unclosed Github issues here serve as our public backlog.

**Comment by jamesmcq** [comment]
Hi All,

Our current version of the plugins contain features to support multi-tenancy. Azure multi-tenancy is a setting you can enable in Azure and is separate from the Moodle side, however this will open access to *any* tenant worldwide. What we've implemented to support multi-tenancy is restrictions on the Moodle side so you can enable Azure multi-tenancy and limit the tenants to your choice. 

In the OpenID Connect plugin there is now a user restrictions feature. This will take regular expressions, one per line, that are matched against users logging in. If set, a user must match at least one of these restrictions to complete the login. Add patterns here to match your desired tenants to restrict users to those of your choosing after enabling multi-tenancy in Moodle.

Please let me know how this works for you and whether you need any other changes to support your intended use case. Closing this issue, please create a new issue if you encounter any issues or need other solutions for your needs.

Thanks!

**Comment by veshant** [comment]
Hi James,
Thats great!  I'll have a go at it and let you know how it works for me.  Thanks!

**Comment by veshant** [comment]
Hey James,

I have tried it out, but I keep getting the error "Auth code not received." when I try to login using another tenant.  I have enabled multi-tenant in the application in Azure, and I have not set any restrictions yet in Moodle OIDC.

**Comment by jamesmcq** [comment]
Hi Veshant - sent you an email. Thanks!

**Comment by veshant** [comment]
Works now.  To resolve, just had to launch OneNote using the admin account of the other tenant.  This is because the "OneNote since APIs are not automatically added to all AAD tenants yet".

Thanks for all your help James.
