### ISSUE TITLE
Plugins do not contain installation instructions

### ISSUE THREAD

**Issue by bbusschots-nuim** [MSOpenTech/o365-moodle#53]
Normally, Moodle plugins contain a text file stating where in the Moodle file system the plugin should be installed. This information is usually either in README.txt or INSTALL.TXT (or .md).

I have no idea which folders to put where, and I have never come across a plugin before that does not contain instructions for where it should go!

**Comment by RobDolinMS** [comment]
Thanks for reaching-out @bbusschots-nuim.  I'm tagging @jamesmcq to take a look.

**Comment by jamesmcq** [comment]
Thanks for the feedback @bbusschots-nuim, this repository actually contains many plugins and the folder structure of this repository mirrors that a Moodle installation, indicating where the plugins should go. For example, in this repository there's an "auth" folder, which contains an "oidc" folder - this "oidc" folder would be placed in the "auth" directory of your Moodle installation. 

Hope that clears it up - I'll add a section in the README file that details this for future reference.

**Comment by jamesmcq** [comment]
Fixed in master, will be in the next release. Thanks for the report!
