### ISSUE TITLE
Moodle reports Missing Permissions

### ISSUE THREAD

**Issue by eabcdev** [MSOpenTech/o365-moodle#57]
Hi Team,

We have Moodle 2.7 with latest plugins version. We have all delegated permissions enabled in Azure (25 for unified API and 11 for sharepoint online, and 8 for Azure Active Directory).

When we check Azure Setup: local_o365 | azuresetup in /admin/settings.php?section=local_o365

This are some missing permissions we get:

Unified API: Directory.ReadWrite.All
Windows Azure Active Directory: UserProfile.Read

Is it maybe cause some changes in Azure since plugins last version? How can we fix it? could be usable if you share your Azure Manifest with the plugins here in the repository?

Best,
Gabriel

**Comment by jamesmcq** [comment]
Hi eabcdev,

These permissions were renamed on the Azure side and the Azure setup tool needs an update to check for the new names. This will be updated in the next release. Azure should have migrated all registered applications using the old permissions so it shouldn't cause any functionality issues other than the report in the Azure setup tool.

Thanks,
- James
