### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by eabcdev** [MSOpenTech/o365-moodle#59]
Hi Team,

We are translating Moodle 2.7 O365 plugins to spanish. We can not update it into moodle.org cause last plugins version is not in that repository, how can we proceed with this changes?

Best,
Gabriel

**Comment by jamesmcq** [comment]
Hi eabcdev, 

We had some issues delaying deploying the newest versions to the Moodle plugin database, however these have been resolved and the newest versions available here on Github should be in the Moodle plugin database by tomorrow.

Thanks,
- James
