### ISSUE TITLE
OneNote Feedback mandatory

### ISSUE THREAD

**Issue by eabcdev** [MSOpenTech/o365-moodle#60]
Hi team, 

Hi team, We have Moodle 2.7 with latest plugins version. 

Testing OneNote Feedback, we noticed that updating some feedback for every student is mandatory in onenote case, when it is not in other task feedback settings. This message is obtained if teacher does not include OneNote feedback for some student:

![image](https://cloud.githubusercontent.com/assets/14235324/10611480/b471fefa-7722-11e5-8116-0144c5828dcd.png)

Is this a design decision, or are we having some bug in our installation?
best
Gabriel

**Comment by jamesmcq** [comment]
Thanks Gabriel, I've added this to our backlog of issues to look at - should be worked on shortly.

**Comment by jamesmcq** [comment]
The latest release should fix this issue. Thanks for the bug report!
