### ISSUE TITLE
Bad Moodle login redirection 

### ISSUE THREAD

**Issue by eabcdev** [MSOpenTech/o365-moodle#61]
Hi Team,
Hi team, We have Moodle 2.7 with latest plugins version. 

We get an error when accessing moodle from O365, because moodle users are redirected to this URI
/auth/oidc/ucp.php

This happends when:
1- User is logged in into office.
2- He goes into Moodle from App Launcher Icon (it workds ok)
3- Closes Moodle Window
4- Then goes from Office to Moodle again, like in step 2

User is redirected to 
/auth/oidc/ucp.php
With an error message that sais that the user has not permissions for "Manage OpenID Connect Connection"

best
Gabriel

**Comment by jamesmcq** [comment]
Thanks Gabriel, I've added this to our backlog of issues to look at - should be worked on shortly.

**Comment by jamesmcq** [comment]
The latest release should fix this issue. Thanks for the bug report!
