### ISSUE TITLE
Onedrive & Microsoft blocks error unless user has set up Onedrive for Business

### ISSUE THREAD

**Issue by wawrobf** [MSOpenTech/o365-moodle#63]
A new user who has not yet visited Onedrive for Business and had it setup will see the following displayed in both the Microsoft and Onenote blocks:

stdClass Object ( [code] => 30105 [message] => OneDrive for Business is not provisioned for this user. [@api.url] => http://go.microsoft.com/fwlink/?LinkId=533061 )

There should be friendlier error handling of this case

**Comment by jamesmcq** [comment]
Thanks wawrobf - We've just fixed this issue and improved the display of error messages there. Look for a fix in the next release, expected Nov. 16th

**Comment by jamesmcq** [comment]
This has been released - can you update to the newest plugins and try it out? If there is still a problem please create a new issue. Thanks!
