### ISSUE TITLE
Moodle Tile in the main Office 365 App Launcher 

### ISSUE THREAD

**Issue by arianalidagarcia** [MSOpenTech/o365-moodle#64]
Need to know how to add, as admin, the Moodle tile in the main app launcher for all users at once without any end user intervention.

**Comment by rlcharles** [comment]
There is an option for this in testing and will be available in a future release.

**Comment by jamesmcq** [comment]
Hi Ariana,

This feature is available in the current release as part of the user sync. Visit the Office 365 Integration Local Plugin settings page and you should see a new option "Assign users to application during sync" for the user sync setting. Enable this and users will be assigned to the configured Azure application during the next user sync. This will make Moodle show up for users in the "my apps" section in Office 365.

Thanks for the feature request!
- James
