### ISSUE TITLE
$plugin->requires  version numbering

### ISSUE THREAD

**Issue by BenKelada** [MSOpenTech/o365-moodle#65]
Hey thanks for the plugins!
Quick comment re versioning, i notice that each moodle release you bump the $plugin->requires to the major milestone release, even though code hasnt change that actually requires the new moodle version.
This has the effect of for example the master version of the plugins not being able to be installed by default on moodle 2.9 even though it is fully compatible.
if this was intentional for major versioning and future proofing, then cool just close and ignore this issue.
But if i can suggest only bumping the the ->requires version if changes are made to code that are dependant on that version of moodle 
thanks again,
Cheers
Ben K

**Comment by jamesmcq** [comment]
Hi Ben, 

We only use master for absolute newest code - sometimes pre-release (although stable) code. For the stable version we mirror what Moodle does - use MOODLE_XX_STABLE branches, which set their $plugin->requires to the appropriate version for that Moodle version, for example, MOODLE_29_STABLE contains the latest release for Moodle 2.9, and the version file requires the Moodle 2.9 version number. There's a bit more info in the repository README. The master branch is set to the latest Moodle version as we sometimes make changes in preparation for the next major Moodle release ahead of time so we can release asap.

Hope that helps!
- James
