### ISSUE TITLE
Latest versions of Office 365 plugins for Moodle 2.8 causes looping bug

### ISSUE THREAD

**Issue by daemonhunt** [MSOpenTech/o365-moodle#66]
I just updated all the Microsoft Office 365 stable of plugins to their latest versions on Moodle 2.8+ :
Office 365 Integration (local_office365) version 2015011608
OpenID Connect (auth_oidc) version 2015011623
Microsoft Office 365 Integration (local_o365) version 2015011636
OneDrive for Business (repository_office365) version 2015011610
Office 365 Connection (profilefield_o365) version 2015011604
OpenIDConnect Management (profilefield_oidc) version 2015011604

One of these is causing an issue where this error keeps appearing:
OpenID Connect
Please set application credentials in auth_oidc first.

If I open auth_oidc to check/update it's confguration, it just gives me the error above instead of letting me adjust the settings. It's pretty much giving an error about itself and it won't let me adjust the settings it is complaining about.

Some of my other plugins (non-miscrosoft ones such as Kaltura Video resource) also aren't working because this error comes up when I use them!

My debug log simply shows this over and over again:
[01-Dec-2015 02:06:26 UTC] Default exception handler: Please set application credentials in auth_oidc first. Debug: 
Error code: erroracpauthoidcnotconfig
* line 68 of /local/o365/classes/oauth2/clientdata.php: moodle_exception thrown
* line 55 of /repository/office365/lib.php: call to local_o365\oauth2\clientdata::instance_from_oidc()
* line 646 of /repository/lib.php: call to repository_office365->__construct()
* line 1131 of /repository/lib.php: call to repository::get_repository_by_id()
* line 3278 of /repository/lib.php: call to repository::get_instances()
* line 394 of /lib/form/filemanager.php: call to initialise_filepicker()
* line 8603 of /lib/adminlib.php: call to form_filemanager->__construct()
* line 1497 of /lib/adminlib.php: call to admin_setting_configstoredfile->output_html()
* line 125 of /admin/settings.php: call to admin_settingpage->output_html()

If I can't update auth_oidc, how can I stop this error with auth_oidc?

Also I can't for the life of me uninstall many of these plugins, so that doesn't work! I wanted to roll back to previous versions and I don't have the latest latest DB to roll back to so this isn't convenient at all.

Regards

**Comment by jamesmcq** [comment]
Hi Daemon - Do you have the OneDrive for Business repository enabled? If so, disable it. This should resolve the issue.

**Comment by daemonhunt** [comment]
Hi jamesmcq, the only problem is that when I go to disable it, the repo throws the error again. 'Please set application credentials in auth_oidc first.'

Would disabling it through the database work perhaps?

**Comment by jamesmcq** [comment]
Ah that would make it difficult to disable wouldn't it. Disabling it in the database can be tricky - try entering dummy data as the client id and client secret in openid connect and saving it - this should at least get you past the error to where you can disable the repository from the UI.

**Comment by jamesmcq** [comment]
Should note as well that we are aware of this issue and current working on a code fix.

**Comment by daemonhunt** [comment]
Ok, entering dummy data as the client id and client secret in openid connect didn't work. I entered dummy data in the database and still had the issue.

However, I did go to the mdl_repository table and set 'visible' to 0 and this disabled the OneDrive 4B repo and now the error has gone away and I can edit the auth_oidc settings again through the Moodle interface.

What a bug!

**Comment by jamesmcq** [comment]
Hi Daemon,

The latest release should resolve the issue - can you update and let me know if you are still experiencing issues? 

Thanks!
